version: "3.8"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    ports:
      - "3000:3000"
    volumes:
      - ./models:/app/models
      - ./config.json:/app/config.json # Mount config file
    restart: unless-stopped